// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Data;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(CalculatorContext))]
    [Migration("20251222130841_m_init3")]
    partial class m_init3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApplication2.Data.DataInputVarian", b =>
                {
                    b.Property<int>("ID_DataInputVarian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_DataInputVarian"));

                    b.Property<string>("Num1")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Num2")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Operation")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Result")
                        .HasColumnType("varchar(128)");

                    b.HasKey("ID_DataInputVarian");

                    b.ToTable("DataInputVarians");
                });
#pragma warning restore 612, 618
        }
    }
}
